In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/kevinnumanzor17/etl-data-pipeline-2522192022/refs/heads/main/data/raw/B_productos.csv"

df = pd.read_csv(url)

df.head()

  id_producto       producto  precio id_proveedor
0      PR1000       Router 0  625.11         P325
1      PR1001      Teclado 1   61.12          NaN
2      PR1002        Mouse 2  203.71         P305
3      PR1003      Teclado 3  886.95         P304
4      PR1004   Impresora 4   103.94         P304

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   146 non-null    object
 1   producto      146 non-null    object
 2   precio        139 non-null    object
 3   id_proveedor  137 non-null    object
dtypes: object(4)
memory usage: 4.7+ KB

id_producto     0
producto        0
precio          7
id_proveedor    9
dtype: int64

In [4]:
import pandas as pd

productos = df.copy()

# limpiar nombres de columnas
productos.columns = productos.columns.str.strip().str.lower()

# limpiar espacios en texto
for col in productos.select_dtypes(include='object').columns:
 productos[col] = productos[col].astype(str).str.strip()

# convertir vacíos en null
productos = productos.replace(r'^\s*$', pd.NA, regex=True)

# eliminar duplicados
productos = productos.drop_duplicates()

In [5]:
# eliminar texto del precio (USD, dólares, etc.)
productos['precio'] = productos['precio'].str.replace(r'[^0-9.]', '', regex=True)

# convertir a numérico
productos['precio'] = pd.to_numeric(productos['precio'], errors='coerce')

In [6]:
validos = productos[
productos['id_producto'].notna() &
productos['producto'].notna() &
productos['precio'].notna() &
productos['id_proveedor'].notna()
].copy()

rechazados = productos[
productos['id_producto'].isna() |
productos['producto'].isna() |
productos['precio'].isna() |
productos['id_proveedor'].isna()
].copy()

In [7]:
def motivo(row):
  motivos = []

  if pd.isna(row['id_producto']):
   motivos.append("producto_id_invalido")

  if pd.isna(row['producto']):
   motivos.append("nombre_vacio")

  if pd.isna(row['precio']):
   motivos.append("precio_invalido")

  if pd.isna(row['id_proveedor']):
   motivos.append("proveedor_vacio")

  return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
validos.to_csv("B_productos_curated.csv", index=False)
rechazados.to_csv("B_productos_rejects.csv", index=False)

In [9]:
url_productos = "https://raw.githubusercontent.com/kevinnumanzor17/etl-data-pipeline-2522192022/refs/heads/main/data/raw/B_productos.csv"

In [10]:
productos = pd.read_csv(url_productos)

In [11]:
productos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   146 non-null    object
 1   producto      146 non-null    object
 2   precio        139 non-null    object
 3   id_proveedor  137 non-null    object
dtypes: object(4)
memory usage: 4.7+ KB

In [12]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 71.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [13]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16")

In [14]:
engine.connect()

In [15]:
import pandas as pd
from sqlalchemy import create_engine

In [16]:
DATABASE_URL = "postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16"

engine = create_engine(DATABASE_URL)

In [17]:
engine.connect()

In [18]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [19]:
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16"

engine = create_engine(DATABASE_URL)

engine.connect()

In [21]:

from sqlalchemy import text

with engine.connect() as conn:
  conn.execute(text("""
CREATE TABLE IF NOT EXISTS productos (
id_producto VARCHAR(10) PRIMARY KEY,
producto VARCHAR(150),
precio NUMERIC,
id_proveedor VARCHAR(10)
);
"""))

conn.commit()

print("Tabla productos creada correctamente")

Tabla productos creada correctamente

In [22]:
validos.to_sql(
"productos",
engine,
if_exists="append",
index=False
)

133

In [23]:
import pandas as pd

pd.read_sql("SELECT * FROM productos LIMIT 10;", engine)

  id_producto     producto  precio id_proveedor
0      PR1000     Router 0  625.11         P325
1      PR1001    Teclado 1   61.12          nan
2      PR1002      Mouse 2  203.71         P305
3      PR1003    Teclado 3  886.95         P304
4      PR1004  Impresora 4  103.94         P304
5      PR1005     Router 5  725.77         P322
6      PR1006     Webcam 6  298.19         P308
7      PR1007     Router 7  470.21         P334
8      PR1008  Disco SSD 8  349.99         P319
9      PR1009  Audífonos 9  430.03         P334